preset: default

# Generated for examples/simple_trainer.py.
data_dir: "/home/wuyou/remote/colmap/output/park_camera_ab/d_ba_k_ba_pose"
data_factor: 4
frame_id_min: 63
frame_id_max: 187
test_every: 16
normalize_world_space: false

result_dir: results/park_0810
disable_viewer: true
disable_video: true

camera_model: fisheye
keep_distortion: true
max_fisheye_fov: 178.0

max_steps: 30000
eval_steps: [3000, 7000, 15000, 30000]
save_steps: [7000, 15000, 30000]
save_ply: true
ply_steps: [7000, 15000, 30000]

sh_degree: 0
ssim_lambda: 0.2
with_geer: true
with_ut: false
with_eval3d: true

init_type: lidar
init_lidar_path: "/home/wuyou/remote/colmap/output/park_camera_ab/d_ba_k_ba_pose/lidar.ply"
init_opa: 0.1
init_scale: 1.0
init_use_knn_pca: true
knn_pca_k: 24
knn_pca_normal_scale_factor: 0.25
knn_pca_planarity_threshold: 0.30
knn_pca_curvature_threshold: 0.10

sky_enabled: true
sky_mask_dir: semantic_masks/sky
sky_num_points: 100000
sky_radius: 10000.0
sky_initial_opacity: 0.7
sky_sh0_lr: 0.0025
sky_shN_lr: 0.000125
sky_alpha_lambda: 0.1

opacity_reg: 0.0
scale_reg: 0.0

strategy:
  absgrad: true
  max_gaussians: 4000000
  max_grow_per_refine: 100000
  refine_stop_iter: 25000
  refine_scale2d_stop_iter: 25000
